# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activetiger}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Drew Olson"]
  s.date = %q{2009-08-27}
  s.description = %q{ActiveTiger allows you to simply add payment processing to your application using Tiger Payment Solutions}
  s.email = %q{development@inventables.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "lib/activetiger.rb",
     "lib/activetiger/configuration.rb",
     "lib/activetiger/gateway.rb",
     "lib/activetiger/response.rb",
     "spec/activetiger/configuration_spec.rb",
     "spec/activetiger/gateway_spec.rb",
     "spec/activetiger/response_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/drewolson/activetiger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easy integration with Tiger Payment Solutions}
  s.test_files = [
    "spec/activetiger/configuration_spec.rb",
     "spec/activetiger/gateway_spec.rb",
     "spec/activetiger/response_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<adamwiggins-rest-client>, [">= 1.0.4"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<adamwiggins-rest-client>, [">= 1.0.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<adamwiggins-rest-client>, [">= 1.0.4"])
  end
end
